[PROLOGUE] Starting prologue on node gpgpu01 at date Tue Oct  3 12:55:08 UTC 2023
[PROLOGUE] Ending prologue on node gpgpu01 at date Tue Oct  3 12:55:08 UTC 2023
stty: standard input: Inappropriate ioctl for device
Version d'EPO : /home/ad/barrouz/EPO_CUR/EPO.
load conda/4.5.4  : OK 
INPUT_LIST_PATH /home/ad/barrouz/WORKSPACE/TIMESERIES_PROJECT/snow_code/performances/tmp/31TGL_inputs.txt
TILE 31TGL
MODELS_PATH /home/ad/barrouz/WORKSPACE/TIMESERIES_PROJECT/snow_code/models
DEM_PATH /work/CAMPUS/etudes/Neige/DEM
TCD_PATH /datalake/static_aux/TreeCoverDensity
start
/home/ad/barrouz/zacharie/TIMESERIES_PROJECT/LANDSAT_QA_DLR/ALP/195029/LT05_L2SP_195029_19990530_20211205_02_T1_snowclass_QA.tif
/home/ad/barrouz/datalake/theia/prod/SPOTWORLDHERITAGE/1999/05/30/SPOT1-HRV1-XS_19990530-110632-362_L1C_048-259-2_D_V1-0/SPOT1-HRV1-XS_19990530-110632-362_L1C_048-259-2_D_V1-0.zip
/tmp/pbs.53253418.admin01/INPUT/LT05_L2SP_195029_19990530_20211205_02_T1_snowclass_QA.tif
/tmp/pbs.53253418.admin01/INPUT/SPOT1-HRV1-XS_19990530-110632-362_L1C_048-259-2_D_V1-0.zip
run script
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/ad/barrouz/WORKSPACE/TIMESERIES_PROJECT/snow_code/snow-swh/perf_inference.py", line 357, in <module>
    prob_classes = net(tensor.to(device=device, dtype=torch.float32))
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ad/barrouz/WORKSPACE/TIMESERIES_PROJECT/snow_code/snow-swh/unet/unet_model.py", line 43, in forward
    x = self.up2(x, x3)
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ad/barrouz/WORKSPACE/TIMESERIES_PROJECT/snow_code/snow-swh/unet/unet_parts.py", line 71, in forward
    return self.conv(x)   #with padding = same ->  output size = input, output trash pixels line/col = input trash pixels + (kernel size -1)
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ad/barrouz/WORKSPACE/TIMESERIES_PROJECT/snow_code/snow-swh/unet/unet_parts.py", line 25, in forward
    return self.double_conv(x)
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (406 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
/home/ad/barrouz/zacharie/TIMESERIES_PROJECT/LANDSAT_QA_DLR/ALP/195029/LT05_L2SP_195029_19920424_20200915_02_T1_snowclass_QA.tif
/home/ad/barrouz/datalake/theia/prod/SPOTWORLDHERITAGE/1992/04/24/SPOT1-HRV2-XS_19920424-104022-605_L1C_049-258-4_D_V1-0/SPOT1-HRV2-XS_19920424-104022-605_L1C_049-258-4_D_V1-0.zip
/tmp/pbs.53253418.admin01/INPUT/LT05_L2SP_195029_19920424_20200915_02_T1_snowclass_QA.tif
/tmp/pbs.53253418.admin01/INPUT/SPOT1-HRV2-XS_19920424-104022-605_L1C_049-258-4_D_V1-0.zip
run script
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
  warn(f"Failed to load image Python extension: {e}")
/home/ad/barrouz/zacharie/TIMESERIES_PROJECT/LANDSAT_QA_DLR/ALP/195029/LT05_L2SP_195029_19980511_20200909_02_T1_snowclass_QA.tif
/home/ad/barrouz/datalake/theia/prod/SPOTWORLDHERITAGE/1998/05/11/SPOT1-HRV1-XS_19980511-104823-587_L1C_050-258-0_D_V1-0/SPOT1-HRV1-XS_19980511-104823-587_L1C_050-258-0_D_V1-0.zip
/tmp/pbs.53253418.admin01/INPUT/LT05_L2SP_195029_19980511_20200909_02_T1_snowclass_QA.tif
/tmp/pbs.53253418.admin01/INPUT/SPOT1-HRV1-XS_19980511-104823-587_L1C_050-258-0_D_V1-0.zip
run script
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
/work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /work/scratch/barrouz/conda_env/pl_lightning/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
  warn(f"Failed to load image Python extension: {e}")
unload conda/4.5.4  : OK 
Traceback (most recent call last):
  File "/home/ad/barrouz/WORKSPACE/TIMESERIES_PROJECT/snow_code/snow-swh/perf_dataframe.py", line 110, in <module>
    cm = confusion_matrix(df1["LANDSAT"],df1["SPOT"],labels=np.unique(df1["LANDSAT"].to_numpy()))
  File "/softs/rh7/conda-envs/pangeo_202211/lib/python3.9/site-packages/sklearn/metrics/_classification.py", line 317, in confusion_matrix
    raise ValueError("'labels' should contains at least one label.")
ValueError: 'labels' should contains at least one label.
cp: cannot stat '/tmp/pbs.53253418.admin01/DF/timeserie_31TGL.pkl': No such file or directory
[EPILOGUE] Starting epilogue on node gpgpu01 at date Tue Oct  3 12:56:45 UTC 2023

------------ JOB INFO 53253418.admin01 -------------

JOBID		: 53253418.admin01
USER		: barrouz
GROUP		: cesbio
JOB NAME	: LANDSAT
SESSION		: 163620
RES REQSTED	: ncpus=8,mem=196gb,walltime=11:59:59,place=free
RES USED	: cpupercent=7,cput=00:01:01,ncpus=8,vmem=2502864kb,mem=2502864kb,walltime=00:01:30
BILLING         : 00:12:00 (ncpus x walltime)
QUEUE		: qgpgpu
ACCOUNT		: null
JOB EXIT CODE	: 1

------------ END JOB INFO 53253418.admin01 ---------

[EPILOGUE] Ending epilogue on node gpgpu01 at date Tue Oct  3 12:56:45 UTC 2023
